werf/3p-helm

- pkg/kube/client.go
The original cleanup on fail would only run if creating a new resource caused an error.
A related problem that was not addressed is that if --wait is set, and the update of a resource times out (for example due to a failed deployment), Helm also won't register the resource. This triggers the same no RESOURCE with the name NAME found on the next deployment.
This PR move the cleanup logic to a method, and then makes sure to call it after the Wait call, in case it finishes on error.
> Add cleanup on fail when waiting for deployment

- pkg/kube/client.go
- pkg/kube/wait.go
Extend `kube.Client` implementation of `environment.KubeClient` interface with ResourcesWaiter object.
ResourcesWaiter interface defines `WaitForResources` and `WatchUntilReady` methods and allows to redefine default waiting behaviour in custom helm builds. For example, to add logging of resources statuses, errors, pod's logs while waiting.
> Customizable resources waiting behaviour for `kube.Client` struct

- pkg/kube/client.go
- Create two-pass patch as follows: current object => apply 2 way merge helm patch => create 3 way merge first stage repair patch => apply first stage repair patch => create actual repair patch.
- Filter out unnecessary fields during patch creation (such as volumeClaimTemplates, empty container/env values).
- Normalize numeric limits and (100Gi, 1000m, etc.).
- Ignore resource *.resources and *.replicas fields optionally.
> [3-way-merge] Create two pass 3wm repair patch: fix false-positive repair patches; ignore resource *.resources and *.replicas fields optionally

- pkg/chartutil/load.go
The problem occurs when the following conditions are met:
* A chart does not contain Chart.yaml file.
* There is an invalid sub chart that does not pass validation.
resolve https://github.com/flant/werf/issues/2388
> Fix panic during sub chart validation

- cmd/helm/install.go
- cmd/helm/upgrade.go
- pkg/cli/values/options.go
[helm for werf] Return action struct for install / upgrade commands
[helm for werf] Support RawValues and RawValuesOverride for ValueOptions to pass map of values directly without CLI-params
[helm for werf] Export ValueOpts option for Install / Upgrade
> [helm for werf] More exports and additions

- cmd/helm/chart_save.go
- cmd/helm/create_test.go
- cmd/helm/exports.go
- cmd/helm/install.go
- cmd/helm/package_test.go
- cmd/helm/template.go
- cmd/helm/upgrade.go
- cmd/helm/upgrade_test.go
- internal/experimental/registry/cache.go
- pkg/action/dependency.go
- pkg/action/package.go
- pkg/action/show.go
- pkg/chart/chart.go
- pkg/chart/chart_extender.go
- pkg/chart/loader/archive.go
- pkg/chart/loader/directory.go
- pkg/chart/loader/load.go
- pkg/chartutil/coalesce.go
- pkg/chartutil/create.go
- pkg/chartutil/create_test.go
- pkg/chartutil/dependencies_test.go
- pkg/chartutil/save_test.go
- pkg/cli/values/options.go
- pkg/downloader/manager.go
- pkg/lint/rules/template.go
- pkg/provenance/sign.go
- pkg/repo/chartrepo.go
- pkg/repo/index.go
- Patched loader.Load function to accept ChartExtender-interfaced object and factory to create extender for subcharts.
- ChartExtender allows adding extra templates and values, generation of Chart.yaml.
> [helm for werf] Added ChartExtender support into Chart to implement WerfChart extensions

- pkg/tiller/release_update.go
errPending on upgrade could occur when some deploy has been interrupted by a signal.
In this case helm leave release in inconsistent state which could not be healed by automatical redeploy.
Werf uses own distributed release locking by release name using Kubernetes configmap annotations to synchronize multiple deploy processes. Werf implementation supports interrupting of werf-deploy process by some signal.
https://github.com/helm/helm/issues/8987
> [v2.17.0][helm for werf] Remove errPending on upgrade

- pkg/action/upgrade.go
errPending on upgrade could occur when some deploy has been interrupted by a signal.
In this case helm leave release in inconsistent state which could not be healed by automatical redeploy.
Werf uses own distributed release locking by release name using Kubernetes configmap annotations to synchronize multiple deploy processes. Werf implementation supports interrupting of werf-deploy process by some signal.
https://github.com/helm/helm/issues/8987
> [v3.4.0][helm for werf] Remove errPending on upgrade

- cmd/helm/chart_save.go
- cmd/helm/create_test.go
- cmd/helm/exports.go
- cmd/helm/install.go
- cmd/helm/package_test.go
- cmd/helm/show.go
- cmd/helm/template.go
- cmd/helm/upgrade.go
- cmd/helm/upgrade_test.go
- internal/experimental/registry/cache.go
- internal/resolver/resolver.go
- pkg/action/dependency.go
- pkg/action/package.go
- pkg/action/show.go
- pkg/chart/loader/archive.go
- pkg/chart/loader/directory.go
- pkg/chart/loader/load.go
- pkg/chartutil/create.go
- pkg/chartutil/create_test.go
- pkg/chartutil/dependencies_test.go
- pkg/chartutil/save_test.go
- pkg/downloader/manager.go
- pkg/lint/rules/dependencies.go
- pkg/lint/rules/template.go
- pkg/provenance/sign.go
- pkg/repo/chartrepo.go
- pkg/repo/index.go
This change will ease fetching of origin helm codebase from the upstream.
> [helm for werf] Refactor LoadOptions passing: use global loader.GlobalLoadOptions variable

- pkg/action/install.go
- pkg/kube/client.go
- pkg/kube/fake/printer.go
- pkg/kube/interface.go
Allow case when namespace already exists in the cluster and user does not have a permission to create namespaces. `helm install --create-namespace` would not try to create namespace in such case.
This change makes `--create-namespace` flag behaviour moreidempotent.
> [werf for helm] Fix --create-namespace flag RBAC issue

- pkg/storage/storage.go
Fixed old releases rotation procedure to not require a deployed release to exists.
An error will arise when there are no successfully deployed release yet, but releases history limit has been reached. In such situation helm will refuse to upgrade release anymore with "... has no deployed releases" error.
Furthermore, release rotation procedure already expecting lastDeployedRelease to be either nil, or not nil. So it is assumed that deployed release may exist or may not and these both outcomes were already expected as a valid situation rather than a failure.
> fix: "... has no deployed releases" error when release history limit reached on initial installation

- pkg/action/upgrade.go
Create a patch from previous release revision no matter succeeded it was or failed, rather than always creating a patch from the previous succeeded release revision.
Affect following cases:
- https://github.com/werf/werf/issues/3461
- https://github.com/werf/werf/issues/3462
> fix: fixed broken 3 way merge when previous release was failed

- pkg/kube/client.go
- pkg/kube/extensions.go
Ignore dry-run related errors for admission webhooks.
These errors may only occur in kubernetes versions prior 1.22.
> fix(server-dry-run): fix "admission webhook ... does not support dry-run"

- pkg/action/install.go
- pkg/action/rollback.go
- pkg/action/uninstall.go
- pkg/action/upgrade.go
- pkg/kube/resource.go
Do not use copy with marshal-unmarshal mechanics, instead prepare separate resource lists twice: for dry-run operation and regular operation.
Signed-off-by: Timofey Kirillov <timofey.kirillov@flant.com>
> fix(server-dry-run): rework dry-run resource lists preparations

- pkg/action/install.go
- pkg/action/rollback.go
- pkg/action/uninstall.go
- pkg/action/upgrade.go
- pkg/kube/resource.go
Do not use copy with marshal-unmarshal mechanics, instead prepare separate resource lists twice: for dry-run operation and regular operation.
Signed-off-by: Timofey Kirillov <timofey.kirillov@flant.com>
> [port from v3.8.0 branch] fix(server-dry-run): rework dry-run resource lists preparations

- pkg/chartutil/dependencies.go
Refactor export-values/import-values logic. Now export-values expand from
the top chart to the most nested ones, unlike import-values that have
it reversed (import-values flow didn't change). Now export-values can be
chained and passed through multiple charts, where you define
export-values directive in each chart of the chain. Import-values
already work like that.
Signed-off-by: Ilya Lesikov <ilya@lesikov.com>
**What this PR does / why we need it**:
**Special notes for your reviewer**:
**If applicable**:
> fix(export-values): broken chaining

- pkg/action/upgrade.go
Helm does not remove env-variable if pre-upgrade hook failed in the first deploy and succeeded next time.
More info about the case: https://github.com/werf/werf/issues/4155
Signed-off-by: Timofey Kirillov <timofey.kirillov@flant.com>
> fix(helm for werf): solved broken 3 way merge case when pre-upgrade hook fails

- cmd/helm/upgrade.go
- pkg/action/upgrade.go
IgnorePending option used by the werf to prevent helm's optimistic locking.
> refactor(helm for werf): make IgnorePending an option for upgrade to fix upgrade unit test

- cmd/helm/install.go
- cmd/helm/rollback.go
- cmd/helm/upgrade.go
- pkg/action/install.go
- pkg/action/rollback.go
- pkg/action/upgrade.go
- pkg/kube/client.go
- pkg/phases/phasemanagers/rollout_phase_manager.go
Fixed:
* Half-succeeded deploys that created new resources won't break
subsequent deploys.
* Created/Updated/Deleted internal Result resource lists were not
consistent — now they represent what was actually done.
* CleanupOnFail now deletes only resources from the current stage
instead of all stages.
Changed:
* CleanupOnFail now triggers only while applying manifests and
won't be triggered while tracking resource progress (for easier
debugging by user).
New:
* CleanupOnFail option for Install.
> fix: cleanupOnFail imrovements

- pkg/downloader/manager.go
Set AllowMissingRepos flag for dependency manager Build operation to disable errors when using unknown to helm repositories in the Chart.yaml dependencies.
> feat(helm-for-werf): allow usage of unmanaged helm repos in dependency building
